### ISSUE TITLE
Missing presets in this webpack target

### ISSUE THREAD

**Issue by Jack-Works** [crimx/neutrino-webextension#19]
Hi! I'm trying to migrate our existing webpack webextension project on to this library, but I found there are some errors. I don't know if it is lacking some plugins.

Errors including:

*   Buffer is not defined
*   process is not defined
*   global is not defined

I know these are Node variables but maybe the "web" target provides these to make packages to build. Can you also provide these plugins too?

**Comment by crimx** [comment]
> Errors including

Where did these errors occur? Are they runtime errors or webpack bundling errors?

> maybe the "web" target provides these to make packages to build

AFAIK "web" target does not provide these globals. This preset use a custom target but never the less these variables must be from some kind of plugin. You may add them yourself. It is quite easy to extend webpack config with neutrino though.

**Comment by Jack-Works** [comment]
Sorry I didn't notice that I need to pass `nodeConfig` to the plugin. I passed it to the Webpack config so it doesn't work
